resource "local_file" "inventory" {
  content = <<-EOT
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    # Node List

    [nginx]
    nginx ansible_host=${yandex_compute_instance.nginx.network_interface.0.nat_ip_address}

    [db01]
    db01 ansible_host=${yandex_compute_instance.db01.network_interface.0.ip_address}

    [db02]
    db02 ansible_host=${yandex_compute_instance.db02.network_interface.0.ip_address}

    [app]
    app ansible_host=${yandex_compute_instance.app.network_interface.0.ip_address}

    [gitlab]
    gitlab ansible_host=${yandex_compute_instance.gitlab.network_interface.0.ip_address}

    [runner]
    runner ansible_host=${yandex_compute_instance.runner.network_interface.0.ip_address}

    [monitoring]
    monitoring ansible_host=${yandex_compute_instance.monitoring.network_interface.0.ip_address}

    # Diplom group

    [myallhosts:children]
    nginx
    db01
    db02
    app
    gitlab
    runner
    monitoring

    [mydb:children]
    db01
    db02

    #
    # Vars for group and hosts
    #

    [nginx:vars]
    my_domain = "${var.my_domain}"
    le_staging = "${var.my_le_staging}"

    [mydb:vars]
    mysql_repl_pass = "${var.mysql_repl_pass}"

    [db01:vars]
    ansible_ssh_common_args='-o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@${yandex_compute_instance.nginx.network_interface.0.nat_ip_address}"'
    mysql_replication_role = "master"

    [db02:vars]
    ansible_ssh_common_args='-o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@${yandex_compute_instance.nginx.network_interface.0.nat_ip_address}"'
    mysql_replication_role = "slave"

    [app:vars]
    ansible_ssh_common_args='-o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@${yandex_compute_instance.nginx.network_interface.0.nat_ip_address}"'
    my_domain = "${var.my_domain}"

    [gitlab:vars]
    ansible_ssh_common_args='-o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@${yandex_compute_instance.nginx.network_interface.0.nat_ip_address}"'
    gitlab_pass = "${var.gitlab_pass}"
    gitlab_runner = "${var.gitlab_runner}"
    my_domain = "${var.my_domain}"

    [runner:vars]
    ansible_ssh_common_args='-o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@${yandex_compute_instance.nginx.network_interface.0.nat_ip_address}"'
    gitlab_runner = "${var.gitlab_runner}"
    my_domain = "${var.my_domain}"

    [monitoring:vars]
    ansible_ssh_common_args='-o ControlMaster=auto -o ControlPersist=10m -o ProxyCommand="ssh -W %h:%p -q ubuntu@${yandex_compute_instance.nginx.network_interface.0.nat_ip_address}"'
    grafana_pass = ${var.grafana_pass}

    [myallhosts:vars]
    my_domain = "${var.my_domain}"
    ip_nginx = ${yandex_compute_instance.nginx.network_interface.0.ip_address}
    ip_db01 = ${yandex_compute_instance.db01.network_interface.0.ip_address}
    ip_db02 = ${yandex_compute_instance.db02.network_interface.0.ip_address}
    ip_app = ${yandex_compute_instance.app.network_interface.0.ip_address}
    ip_gitlab = ${yandex_compute_instance.gitlab.network_interface.0.ip_address}
    ip_runner = ${yandex_compute_instance.runner.network_interface.0.ip_address}
    ip_monitoring = ${yandex_compute_instance.monitoring.network_interface.0.ip_address}

    EOT
  filename = "../ansible/inventory.yml"
  file_permission = "0644"

  depends_on = [
    yandex_compute_instance.nginx,
    yandex_compute_instance.db01,
    yandex_compute_instance.db02,
    yandex_compute_instance.app,
    yandex_compute_instance.gitlab,
    yandex_compute_instance.runner,
    yandex_compute_instance.monitoring
  ]
}
