---
  - name: wait for hosts to up
    hosts: all
    gather_facts: no
    tasks:
      - name: Wait 300 seconds, but only start checking after 60 seconds
        ansible.builtin.wait_for_connection:
          delay: 60
          timeout: 300
        tags: 
          - wait

  - name: Chech connection
    hosts: all
    gather_facts: yes
    #become: true
    tasks:
      - name: Print OS
        debug:
          msg: "{{ ansible_distribution }}"
      - name: Set hostnames
        become: true
        hostname:
          name: "{{ inventory_hostname }}"
          use: "debian"

